---
abstract: 'Asynchronous MongoDB client using AnyEvent'
author:
  - 'Graham Barr'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-MongoDB
requires:
  AnyEvent: 5.271
  Digest::MD5: 0
  List::Util::XS: 0.01
  MongoDB: 0.38
  Moose: 0.98
  Tie::IxHash: 0
  namespace::autoclean: 0
resources:
  repository: git://github.com/gbarr/AnyEvent-MongoDB.git
version: 0.103620_001
